### ISSUE TITLE
NoMethodError in Projects#new

### ISSUE THREAD

**Issue by leegakyeong** [leegakyeong/OP#28]
![image](https://user-images.githubusercontent.com/22510942/43687873-931a5a3e-9918-11e8-9562-9c52884ea4f1.png)

NoMethodError in Projects#new
undefined method `projects_path' for #<#<Class:0x00007fc3e4d07348>:0x00007fc3d411b620>

제가 레일즈 폼 헬퍼를 잘 모르고 찾아봐도 잘 모르겠어섴ㅋㅋㅋㅋ큐ㅠㅠㅠ왜이런걸까요...?

**Comment by ssm0318** [comment]
아잇 제길 ㅠㅠ 저걸 안 없애고 커밋했구나ㅠㅠ 저의 잘못이예요ㅠㅠ 내일까지 쓰레기 줍줍 해놓을게요ㅠㅠ 이전의 new가 갈비쥐라 발전시키려고 했는데 하다 말아서 새로운 쓰레기가 되었어요ㅠ

**Comment by leegakyeong** [comment]
쓰레깈ㅋㅋㅋㅋㅋㅋㅋ아니에요 너무너무 고생하십니당 ㅠㅠㅠㅠbb

**Comment by ssm0318** [comment]
아마 마스터에 있던 에러들이 사라졌을거예요!

**Comment by ssm0318** [comment]
해결했습니다.
